#!/usr/bin/python2

import sys, re, shutil, os, hashlib
import imp
import importlib
import getpass

if __name__ == '__main__':

    d = os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), os.pardir))
    os.chdir(d)
    v = imp.load_source('version', 'lib/version.py')
    version = v.ELECTRUM_VERSION
    print "version", version

    # copy dependencies into 'packages' directory
    deps = [
        'pyaes',
        'ecdsa',
        'pbkdf2',
        'requests', # note: requests-2.5.1 is needed to build with pyinstaller
        'qrcode',
        # 'google.protobuf',
        # 'dns',
        'six',
        'jsonrpclib',
        'socks',
    ]
    for module in deps:
        moduleObj = importlib.import_module(module)
        # f = moduleObj.__file__
        # try:
        #     _, pathname, descr = imp.find_module(module)
        # except ImportError:
        # f = moduleObj.__file__
        pathname =  moduleObj.__name__
        descr = ('.py', '', 5)
        # print "__file__ =", moduleObj.__file__
        print "__name__ =", moduleObj.__name__
        # else:
        #     # assert f == moduleObj.__file__
        #     # assert pathname == moduleObj.__name__
        #     # print "f =", f, ", __file__ =", moduleObj.__file__
        #     print "pathname =", pathname, ", __name__ =", moduleObj.__name__
        #     print 'descr = %s' % (descr,)
        target = 'packages/' + module + descr[0]
        if os.path.exists(target):
            continue
        d = os.path.dirname(target)
        if d and not (os.path.exists(d)):
            os.makedirs(d)
        if os.path.isfile(pathname):
            shutil.copy(pathname, target)
        if os.path.isdir(pathname):
            shutil.copytree(pathname, target, ignore=shutil.ignore_patterns('*.pyc'))
        else:
            raise IOError("no such file or directory: %r")

    # fix google/__init__.py needed by pyinstaller
    n = 'packages/google/__init__.py'
    if not os.path.exists(n):
        os.system("echo \# do not remove>%s"%n)

    # patch requests and add cacert.pem
    import requests
    crt = requests.certs.where()
    n = 'packages/requests/certs.py'
    with open(n, 'r') as f:
        s = f.read()
    s = s.replace("'%s'"%crt, "os.path.join(os.path.dirname(__file__), 'cacert.pem')")
    with open(n, 'w') as f:
	f.write(s)
    shutil.copy(crt, 'packages/requests/cacert.pem')

    os.system("pyrcc4 icons.qrc -o gui/qt/icons_rc.py")
    os.system("python setup.py sdist --format=zip,gztar")

    print "Packages are ready in dist"


